<a href="https://colab.research.google.com/github/Goutham-26/DSA/blob/main/22casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [144]:
import pandas as pd
population = pd.read_csv('/content/population.csv')
population.head()

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [145]:
population.dtypes

country       object
population     int64
dtype: object

In [146]:
population.shape

(25, 2)

In [147]:
gdp = pd.read_excel('/content/gdp.xlsx')
gdp.columns.tolist()

['Country', 'GDP']

In [148]:
gdp.dtypes

Country    object
GDP         int64
dtype: object

In [149]:
internet= pd.read_json('/content/internet_users.json')
internet.head()

         country  internet_users
0  United States       312000000
1          China      1080000000
2          India       850000000
3          Japan       118000000
4        Germany        79000000

In [150]:
pd.DataFrame(internet_df)

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [151]:
literacy = pd.read_xml('/content/literacy_rate.xml')
literacy.head()

            name  literacy_rate
0  United States           99.0
1          China           97.2
2          India           77.7
3          Japan           99.0
4        Germany           99.0

In [152]:
pd.DataFrame(literacy)

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [153]:
exploration_results = {}

datasets = [
    ("Population Dataset", population),
    ("GDP Dataset", gdp),
    ("Internet Users Dataset", internet),
    ("Literacy Rate Dataset", literacy)
]
for name, df in datasets:
    exploration_results[name] = {
        "num_rows": df.shape[0],
        "num_columns": df.shape[1],
        "column_names": df.columns.tolist(),
        "data_types": df.dtypes.to_dict(),
        "missing_values": df.isnull().sum().to_dict(),
        "duplicate_records": int(df.duplicated().sum())
    }
pd.DataFrame(exploration_results)

,Population Dataset,GDP Dataset,Internet Users Dataset,Literacy Rate Dataset
num_rows,25,25,25,25
num_columns,2,2,2,2
column_names,"[country, population]","[Country, GDP]","[country, internet_users]","[name, literacy_rate]"
data_types,"{'country': object, 'population': int64}","{'Country': object, 'GDP': int64}","{'country': object, 'internet_users': int64}","{'name': object, 'literacy_rate': float64}"
missing_values,"{'country': 0, 'population': 0}","{'Country': 0, 'GDP': 0}","{'country': 0, 'internet_users': 0}","{'name': 0, 'literacy_rate': 0}"
duplicate_records,0,0,0,0

In [154]:
population.rename(columns={'country': 'country'}, inplace=True)
gdp.rename(columns={'Country': 'country'}, inplace=True)
internet.rename(columns={'country': 'country'}, inplace=True)
literacy.rename(columns={'name': 'country'}, inplace=True)

In [155]:
population.columns.tolist()

['country', 'population']

In [156]:
gdp.columns.tolist()

['country', 'GDP']

In [157]:
internet.columns.tolist()

['country', 'internet_users']

In [158]:
literacy.columns.tolist()

['country', 'literacy_rate']

In [159]:
merged = population.merge(gdp, on='country', how='inner')
merged = merged.merge(internet, on='country', how='inner')
merged = merged.merge(literacy, on='country', how='inner')
data=pd.DataFrame(merged)
data

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

In [160]:
merged = pd.merge(population, gdp, on='country', how='outer')
merged = pd.merge(merged_df, internet, on='country', how='outer')
merged = pd.merge(merged_df, literacy, on='country', how='outer')

display(merged.head())

,country,population,GDP,internet_users,literacy_rate_x,literacy_rate_y
0,Argentina,45195774,640000,41000000,99.1,99.1
1,Australia,25687041,1880000,24000000,99.0,99.0
2,Brazil,212559417,2330000,181000000,93.2,93.2
3,Canada,38005238,2250000,36000000,99.0,99.0
4,China,1411778724,19230000,1080000000,97.2,97.2

In [161]:
merged['internet_penetration'] = round((merged['internet_users'] / merged['population']) * 100, 2)
merged['gdp_per_capita'] = round(merged['GDP'] / merged['population'], 2)

In [162]:
merged['internet_penetration']

0     90.72
1     93.43
2     85.15
3     94.72
4     76.50
5     94.98
6     94.91
7     61.59
8     77.51
9     92.62
10    93.77
11    79.11
12    97.47
13    97.76
14    85.65
15    97.66
16    95.72
17    72.50
18    96.56
19    94.11
20    97.55
21    98.21
22    81.81
23    97.22
24    94.26
Name: internet_penetration, dtype: float64

In [163]:
merged['gdp_per_capita']

0     0.01
1     0.07
2     0.01
3     0.06
4     0.01
5     0.05
6     0.06
7     0.00
8     0.01
9     0.04
10    0.03
11    0.01
12    0.07
13    0.11
14    0.02
15    0.03
16    0.09
17    0.01
18    0.03
19    0.04
20    0.06
21    0.11
22    0.02
23    0.06
24    0.09
Name: gdp_per_capita, dtype: float64

In [164]:
import sqlite3
conn = sqlite3.connect('country_analytics.db')
merged.to_sql('country_statistics', conn, if_exists='replace', index=False)

25

In [165]:
verification = pd.read_sql_query("SELECT * FROM country_statistics LIMIT 5;", conn)
verification

,country,population,GDP,internet_users,literacy_rate_x,literacy_rate_y,internet_penetration,gdp_per_capita
0,Argentina,45195774,640000,41000000,99.1,99.1,90.72,0.01
1,Australia,25687041,1880000,24000000,99.0,99.0,93.43,0.07
2,Brazil,212559417,2330000,181000000,93.2,93.2,85.15,0.01
3,Canada,38005238,2250000,36000000,99.0,99.0,94.72,0.06
4,China,1411778724,19230000,1080000000,97.2,97.2,76.50,0.01

In [166]:
top_5_gdp = merged.nlargest(5, 'GDP')[['country', 'GDP']]
top_5_gdp

          country       GDP
24  United States  30500000
4           China  19230000
6         Germany   4744000
7           India   4187000
10          Japan   4180000

In [167]:
top_5_population = merged.nlargest(5, 'population')[['country', 'population']]
top_5_population

          country  population
4           China  1411778724
7           India  1380004385
24  United States   331002651
8       Indonesia   273523615
2          Brazil   212559417

In [168]:
average_literacy = merged['literacy_rate_y'].mean()
average_literacy

np.float64(97.24799999999999)

In [169]:
high_literacy = merged[merged['literacy_rate_y'] > 90][['country', 'literacy_rate_y']]
high_literacy

           country  literacy_rate_y
0        Argentina             99.1
1        Australia             99.0
2           Brazil             93.2
3           Canada             99.0
4            China             97.2
5           France             99.0
6          Germany             99.0
8        Indonesia             96.0
9            Italy             99.0
10           Japan             99.0
11          Mexico             95.4
12     Netherlands             99.0
13          Norway            100.0
14          Russia             99.7
15    Saudi Arabia             97.3
16       Singapore             97.5
17    South Africa             95.0
18     South Korea             98.8
19           Spain             98.6
20          Sweden             99.0
21     Switzerland             99.0
22          Turkey             96.7
23  United Kingdom             99.0
24   United States             99.0

In [170]:
high_internet_penetration = merged[merged['internet_penetration'] > 70][['country', 'internet_penetration']]
high_internet_penetration

           country  internet_penetration
0        Argentina                 90.72
1        Australia                 93.43
2           Brazil                 85.15
3           Canada                 94.72
4            China                 76.50
5           France                 94.98
6          Germany                 94.91
8        Indonesia                 77.51
9            Italy                 92.62
10           Japan                 93.77
11          Mexico                 79.11
12     Netherlands                 97.47
13          Norway                 97.76
14          Russia                 85.65
15    Saudi Arabia                 97.66
16       Singapore                 95.72
17    South Africa                 72.50
18     South Korea                 96.56
19           Spain                 94.11
20          Sweden                 97.55
21     Switzerland                 98.21
22          Turkey                 81.81
23  United Kingdom                 97.22
24   United States                 94.26

In [171]:
top_5_gdp_per_capita = merged.nlargest(5, 'gdp_per_capita')[['country', 'gdp_per_capita']]
top_5_gdp_per_capita

          country  gdp_per_capita
13         Norway            0.11
21    Switzerland            0.11
16      Singapore            0.09
24  United States            0.09
1       Australia            0.07

In [172]:
total_population = merged['population'].sum()
total_population

np.int64(4720039725)

In [173]:
average_internet_penetration = merged['internet_penetration'].mean()
average_internet_penetration

np.float64(89.65960000000001)

In [174]:
highest_internet_country = merged.loc[merged['internet_users'].idxmax(), ['country', 'internet_users']]
highest_internet_country

country                China
internet_users    1080000000
Name: 4, dtype: object

In [175]:
correlation_metric = merged['literacy_rate_y'].corr(merged['internet_penetration'])
correlation_metric

np.float64(0.7727975681398502)

In [176]:
conn = sqlite3.connect('country_analytics.db')
cursor = conn.cursor()

In [177]:
q1 = "SELECT country, GDP FROM country_statistics ORDER BY GDP DESC LIMIT 5;"
cursor.execute(q1)
for row in cursor.fetchall():
    print(row)

('United States', 30500000)
('China', 19230000)
('Germany', 4744000)
('India', 4187000)
('Japan', 4180000)

In [178]:
q2 = "SELECT AVG(literacy_rate_y) FROM country_statistics;"
cursor.execute(q2)
print(f"Average Literacy Rate: {cursor.fetchone()[0]:.3f}%")

Average Literacy Rate: 97.248%

In [179]:
q3 = "SELECT country, literacy_rate_y FROM country_statistics WHERE literacy_rate_y > 90;"
cursor.execute(q3)
for row in cursor.fetchall():
    print(row)

('Argentina', 99.1)
('Australia', 99.0)
('Brazil', 93.2)
('Canada', 99.0)
('China', 97.2)
('France', 99.0)
('Germany', 99.0)
('Indonesia', 96.0)
('Italy', 99.0)
('Japan', 99.0)
('Mexico', 95.4)
('Netherlands', 99.0)
('Norway', 100.0)
('Russia', 99.7)
('Saudi Arabia', 97.3)
('Singapore', 97.5)
('South Africa', 95.0)
('South Korea', 98.8)
('Spain', 98.6)
('Sweden', 99.0)
('Switzerland', 99.0)
('Turkey', 96.7)
('United Kingdom', 99.0)
('United States', 99.0)

In [180]:
q4 = "SELECT country, internet_penetration FROM country_statistics ORDER BY internet_penetration DESC LIMIT 5;"
cursor.execute(q4)
for row in cursor.fetchall():
    print(row)

('Switzerland', 98.21)
('Norway', 97.76)
('Saudi Arabia', 97.66)
('Sweden', 97.55)
('Netherlands', 97.47)

In [181]:
q5 = "SELECT SUM(population) FROM country_statistics;"
cursor.execute(q5)
print(f"Total Population: {cursor.fetchone()[0]}")

Total Population: 4720039725

In [182]:
q6 = "SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 1;"
cursor.execute(q6)
print(f"ountry with Highest GDP per Capita: {cursor.fetchone()}")

ountry with Highest GDP per Capita: ('Norway', 0.11)

In [183]:
export = pd.read_sql_query("SELECT * FROM country_statistics;", conn)
export.to_csv('final_country_statistics.csv', index=False)
print("\n17. Final dataset successfully exported to 'final_country_statistics.csv'")

17. Final dataset successfully exported to 'final_country_statistics.csv'

In [184]:
q8 = "SELECT country, gdp_per_capita FROM country_statistics ORDER BY gdp_per_capita DESC LIMIT 10;"
cursor.execute(q8)
print("Top 10 Countries by GDP per Capita:")
for row in cursor.fetchall():
    print(row)

Top 10 Countries by GDP per Capita:
('Norway', 0.11)
('Switzerland', 0.11)
('Singapore', 0.09)
('United States', 0.09)
('Australia', 0.07)
('Netherlands', 0.07)
('Canada', 0.06)
('Germany', 0.06)
('Sweden', 0.06)
('United Kingdom', 0.06)

In [185]:
cursor.close()
conn.close()